-- Supabase Schema for Travel Platform

-- 1. Customers Table
CREATE TABLE IF NOT EXISTS customers (
    id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
    full_name TEXT NOT NULL,
    phone TEXT NOT NULL,
    phone2 TEXT,
    is_verified BOOLEAN DEFAULT FALSE,
    total_rides INTEGER DEFAULT 0,
    last_ride TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Drivers Table
CREATE TABLE IF NOT EXISTS drivers (
    id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
    full_name TEXT NOT NULL,
    phone TEXT NOT NULL,
    whatsapp_number TEXT,
    car_type TEXT,
    car_model TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    verification_status TEXT DEFAULT 'pending',
    total_rides INTEGER DEFAULT 0,
    rating FLOAT DEFAULT 5.0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Cities Table
CREATE TABLE IF NOT EXISTS cities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_ar TEXT NOT NULL UNIQUE,
    is_active BOOLEAN DEFAULT TRUE
);

-- 4. Vehicle Categories Table
CREATE TABLE IF NOT EXISTS vehicle_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_ar TEXT NOT NULL,
    description_ar TEXT,
    price_multiplier FLOAT DEFAULT 1.0,
    icon_emoji TEXT DEFAULT '🚗',
    is_active BOOLEAN DEFAULT TRUE,
    sort_order INTEGER DEFAULT 0
);

-- 5. Ride Requests Table
CREATE TABLE IF NOT EXISTS ride_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id UUID REFERENCES customers(id),
    passenger_name TEXT, -- Denormalized for easy display
    passenger_phone TEXT, -- Denormalized
    from_city TEXT NOT NULL,
    to_city TEXT NOT NULL,
    vehicle_category TEXT,
    estimated_price INTEGER,
    notes TEXT,
    status TEXT DEFAULT 'pending', -- 'pending', 'accepted', 'cancelled'
    driver_id UUID REFERENCES drivers(id),
    driver_name TEXT,
    driver_phone TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    accepted_at TIMESTAMP WITH TIME ZONE
);

-- 6. Rides Table
CREATE TABLE IF NOT EXISTS rides (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    passenger_id UUID REFERENCES customers(id),
    passenger_name TEXT,
    passenger_phone TEXT,
    driver_id UUID REFERENCES drivers(id),
    driver_name TEXT,
    driver_phone TEXT,
    from_city TEXT NOT NULL,
    to_city TEXT NOT NULL,
    vehicle_category TEXT,
    base_price INTEGER,
    final_price INTEGER,
    notes TEXT,
    status TEXT DEFAULT 'accepted', -- 'accepted', 'confirmed', 'completed', 'cancelled'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    accepted_at TIMESTAMP WITH TIME ZONE
);

-- 7. Ride Chats Table
CREATE TABLE IF NOT EXISTS ride_chats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ride_id BIGINT, -- Can reference ride_requests(id) or rides(id) depending on how we want it
    sender_id UUID NOT NULL,
    sender_name TEXT,
    sender_type TEXT, -- 'passenger' or 'driver'
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 8. System Settings Table
CREATE TABLE IF NOT EXISTS system_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT NOT NULL UNIQUE,
    value TEXT
);

-- 9. Activity Logs Table
CREATE TABLE IF NOT EXISTS activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID,
    user_type TEXT,
    action TEXT,
    description TEXT,
    related_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 10. Driver Notifications Table
CREATE TABLE IF NOT EXISTS driver_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id UUID REFERENCES drivers(id),
    title TEXT,
    message TEXT,
    type TEXT,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE drivers ENABLE ROW LEVEL SECURITY;
ALTER TABLE cities ENABLE ROW LEVEL SECURITY;
ALTER TABLE vehicle_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE ride_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE rides ENABLE ROW LEVEL SECURITY;
ALTER TABLE ride_chats ENABLE ROW LEVEL SECURITY;
ALTER TABLE system_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE activity_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE driver_notifications ENABLE ROW LEVEL SECURITY;

-- Basic Policies (Adjust as needed for specific security requirements)
-- Customers can read their own profile
CREATE POLICY "Customers see own profile" ON customers FOR SELECT USING (auth.uid() = id);
-- Drivers can read their own profile
CREATE POLICY "Drivers see own profile" ON drivers FOR SELECT USING (auth.uid() = id);

-- Public/Authenticated reads
CREATE POLICY "Anyone can see cities" ON cities FOR SELECT USING (TRUE);
CREATE POLICY "Anyone can see categories" ON vehicle_categories FOR SELECT USING (TRUE);

-- Ride Requests Policies
CREATE POLICY "Customers can insert requests" ON ride_requests FOR INSERT WITH CHECK (auth.uid() = customer_id);
CREATE POLICY "Customers can see own requests" ON ride_requests FOR SELECT USING (auth.uid() = customer_id);
CREATE POLICY "Drivers can see pending requests" ON ride_requests FOR SELECT USING (status = 'pending' OR driver_id = auth.uid());
CREATE POLICY "Drivers can update status to accept" ON ride_requests FOR UPDATE USING (status = 'pending' OR driver_id = auth.uid());

-- Rides Policies
CREATE POLICY "Participants can see ride" ON rides FOR SELECT USING (auth.uid() = passenger_id OR auth.uid() = driver_id);
CREATE POLICY "Drivers can insert/update rides" ON rides FOR ALL USING (auth.uid() = driver_id);

-- Chat Policies
CREATE POLICY "Participants can see chats" ON ride_chats FOR SELECT USING (
    EXISTS (SELECT 1 FROM rides WHERE id = ride_id AND (passenger_id = auth.uid() OR driver_id = auth.uid()))
    OR
    EXISTS (SELECT 1 FROM ride_requests WHERE id = ride_id AND (customer_id = auth.uid() OR driver_id = auth.uid()))
);
CREATE POLICY "Participants can insert chats" ON ride_chats FOR INSERT WITH CHECK (
    auth.uid() = sender_id
);

-- Initial Data
INSERT INTO vehicle_categories (name_ar, description_ar, price_multiplier, icon_emoji, sort_order) VALUES
('اقتصادي', 'سيارة اقتصادية', 1.0, '🚗', 1),
('مريح', 'سيارة مريحة', 1.3, '🚙', 2),
('عالي / SUV', 'سيارة كبيرة', 1.6, '🚘', 3)
ON CONFLICT DO NOTHING;

INSERT INTO system_settings (key, value) VALUES
('staff_passcode', '1234'),
('platform_name', 'ترحال زونا'),
('service_fee_percentage', '10')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
